/**
 * Downloads the webfonts this site uses from Google Fonts into public/fonts,
 * and writes public/fonts.css with matching @font-face rules.
 *
 * Fonts are self-hosted rather than hotlinked: hotlinking sends every
 * visitor's IP to Google (a GDPR problem for an EU-facing site) and would
 * force third-party origins into the Content-Security-Policy.
 *
 * Run: npm run fonts:fetch
 */
import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

const SPEC =
  'https://fonts.googleapis.com/css2?family=Bodoni+Moda:ital,opsz,wght@0,6..96,400..600;1,6..96,400..500&family=Jost:ital,wght@0,300..600;1,400&display=swap'

// A modern desktop UA makes Google serve woff2 rather than legacy formats.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'

/** Latin covers English; latin-ext covers the Spanish accents. Nothing else is used. */
const KEEP = new Set(['latin', 'latin-ext'])

const OUT_DIR = 'public/fonts'

const css = await fetch(SPEC, { headers: { 'User-Agent': UA } }).then((r) => {
  if (!r.ok) throw new Error(`Google Fonts returned ${r.status}`)
  return r.text()
})

const blocks = [...css.matchAll(/\/\* ([a-z0-9-]+) \*\/\s*(@font-face \{[\s\S]*?\})/g)]
if (blocks.length === 0) throw new Error('No @font-face blocks parsed — did the CSS format change?')

await mkdir(OUT_DIR, { recursive: true })

const rules = []
let count = 0
let bytes = 0

for (const [, subset, block] of blocks) {
  if (!KEEP.has(subset)) continue

  const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)[1]
  const family = block.match(/font-family: '([^']+)'/)[1]
  const style = block.match(/font-style: (\w+)/)[1]
  const weight = block.match(/font-weight: ([\d ]+);/)[1].trim()

  const name = `${family.toLowerCase().replaceAll(' ', '-')}-${style}-${weight.replaceAll(' ', '-')}-${subset}.woff2`
  const data = Buffer.from(await fetch(url, { headers: { 'User-Agent': UA } }).then((r) => r.arrayBuffer()))

  await writeFile(join(OUT_DIR, name), data)
  count += 1
  bytes += data.length

  rules.push(block.replace(/url\(https:\/\/[^)]+\.woff2\)/, `url('./fonts/${name}')`).trim())
}

const header = `/*
 * GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.
 * Regenerate with: npm run fonts:fetch
 *
 * Self-hosted so no visitor request reaches a third-party font CDN.
 * Both families are SIL Open Font License 1.1 — see public/fonts/OFL.txt.
 *
 * Paths are relative to this file, so the site works under any base path.
 */

`

await writeFile('public/fonts.css', header + rules.join('\n\n') + '\n')
console.log(`${count} font files, ${(bytes / 1024).toFixed(0)} KB → ${OUT_DIR}`)
console.log('wrote public/fonts.css')
